### ISSUE TITLE
rule unique-type-names always shows error

### ISSUE THREAD

**Issue by lioneltay** [dotansimha/graphql-eslint#277] opened 2021-01-21 03:14 UTC
The rule requires you provide a schema to the plugin to work against and if it finds any types in your graphql files that are defined in the schema it will tell you it is a duplicate. However, the schema itself is generated from these type definitions, so every type becomes an error as long as you have used it to generate your schema (in the case of a json file), or have deployed the changes to an endpoint (in the case of providing a url as the schema).

I understand that eslint can only look at one file at a time? So I'm not sure how this can be improved... but it doesn't seem very useful as it is. Unless I am missing something...

**Comment by dnalborczyk** [comment] 2021-01-22 14:35
> I understand that eslint can only look at one file at a time? 

`eslint` might, but this plugin pulls in _all_ your schema files and creates an abstract syntax tree which every rule uses.

**Comment by lioneltay** [comment] 2021-01-25 01:31
Is the rule working as intended at the moment? I think the problem is that the plugin is not able to distinguish what is in the schema because it comes from other files, and what is coming from the current file it is linting. It seems to collect your entire schema, then use that to determine whether or not a type already exists, but the schema itself has types from the current file it is linting, so it always results in it saying that the type already exists.

**Comment by dnalborczyk** [comment] 2021-01-27 20:48
@lioneltay just gave it a try myself, it seems this rule is broken.

**Comment by B2o5T** [comment] 2021-04-22 13:41
any news?

**Comment by Urigo** [comment] 2021-04-26 13:00
Thanks for the detailed reports!

I'm not adding a lot here but I'm just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It looks like already got it into `stage 0`! thank you for that! 

Now in order to advance to `stage 1` we'll need a running reproduction.

After that maybe a failing test to advance it through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by B2o5T** [comment] 2021-04-26 13:48
@Urigo thank u ;) I added sample repo https://github.com/B2o5T/graphql-eslint-unique-type-names

**Comment by Urigo** [comment] 2021-04-27 17:52
that's awesome @B2o5T !

For [`stage 2`](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow), we'll need a failing test If someone wants to give it a go: https://github.com/dotansimha/graphql-eslint/tree/master/packages/plugin/tests

**Comment by B2o5T** [comment] 2021-04-27 19:50
@Urigo thank for the links :+1:, I added invalid and valid tests in this PR https://github.com/dotansimha/graphql-eslint/pull/405

**Comment by Urigo** [comment] 2021-04-27 21:32
wow that's so useful @B2o5T ! thank you, moved to stage 2!

**Comment by dotansimha** [comment] 2021-05-18 15:25
Fixed in `v1.0.0`! 🎉

**Closed by dotansimha** 2021-05-18 15:25 UTC
Labels: kind/bug, stage/5-alpha-release-testing
